### ISSUE TITLE
Impossible to run JSRepl on newly created (not saved) file

### ISSUE THREAD

**Issue by VKondakoff** [axilleasiv/vscode-javascript-repl-docs#10]
It is impossible to run JSRepl on newly created (not saved) file. If you run JS Repl: Run command on a new (not yet saved) file which Language Mode is set to, say, JavaScript - you will receive an error: "Use an approriate file to start repl: .js .jsx .vue .ts .tsx .coffee".

<img width="503" alt="Image on 2019-11-14 11 50 21 PM" src="https://user-images.githubusercontent.com/230824/68895315-13ce3480-073a-11ea-9ee1-b4d99629ba36.png">

I'm pretty sure JSRepl should be able to run on a file with set Language Mode without saving it first (and it actually can do this, by creating a new file directly by JSRepl: by using command 'JS Rdpl: New ... file').

**Comment by axilleasiv** [comment]
@VKondakoff Thanks for your feedback about this issue. In version 0.6.2, it is possible now to do this.
