### ISSUE TITLE
Only show run button on the supported files

### ISSUE THREAD

**Issue by dhonx** [axilleasiv/vscode-javascript-repl-docs#16]
Hi ... Very good extension. Worth replacing Quokka JS. :+1: 

I think it will be better if the `run` button will only appear if the current file is supported.

**Comment by axilleasiv** [comment]
Hello, @dhonx thanks for your feedback. I agree with you, it will be better if the 'run' button appears when the current file is supported by the extension. So I am planning to do this to the next version

**Comment by dhonx** [comment]
You're welcome... I'm glad to contribute, can't wait for the next version .👍🙌

**Comment by axilleasiv** [comment]
Added in 0.6.5 version
