### ISSUE TITLE
(Resolved) Not working in create-react-app project

### ISSUE THREAD

**Issue by rohantarai** [axilleasiv/vscode-javascript-repl-docs#19]
![react repl](https://user-images.githubusercontent.com/16543074/89133473-b5501d00-d539-11ea-9fb7-85c8fce277e6.PNG)

As per the description of this extension that says `it can be used for development in Node.js projects or with front-end frameworks like React, Vue, Angular, Svelte etc.`
As you can see i have written a console.log('hello') code inside Grid() function but it doesnt show the value. I tried changing few settings but no results. Can you help me in this. Thanks!

**Comment by axilleasiv** [comment]
Hey @rohantarai from your screenshoot, I think that you have not called the function Grid. Please try to use this function (react component) to some part of your code in order to see the log inside the function or just move the console.log expression outside the function for example at line 6

**Comment by rohantarai** [comment]
Hi @axilleasiv , this is a functional component in reactjs. in the image below you can see i have called this component in App.js file. Still it doesnt work. are you caying to call the grid function like this `Grid()`? I cannot call like this because it is not a normal function. its a component.
[
![Capture](https://user-images.githubusercontent.com/16543074/89457405-f8e99780-d782-11ea-9e27-5afd6253113e.PNG)
](url)

**Comment by axilleasiv** [comment]
@rohantarai in this case please start the extension ("JS Repl: Run") on the App.js file where the Grid component is imported and used.

if you start the extension on the App.js and after that just open the Grid.js file, you should see the result of the console.log expression.

Please tell me if that works for you

**Comment by rohantarai** [comment]
Hi @axilleasiv , Running ("JS Repl: Run") on App,js file didn't worked instead running on `index.js` file which is called as the root file made it working on all the nested components. I didn't need to run it again on any other js file. From root file it ran all other components as well. Thank you very much for this awesome tool. Also it would be nice if you can add this to your docs on "How to use this tool in Reactjs project". So that any other user wouldn't face difficulties to make it work.

**index.js**
![index](https://user-images.githubusercontent.com/16543074/89557912-2ab93780-d831-11ea-9bd5-edd8d5c85ff8.PNG)


**App.js**
![app](https://user-images.githubusercontent.com/16543074/89557943-360c6300-d831-11ea-80a5-adf3ee63e99e.PNG)


**Grid.js**
![grid](https://user-images.githubusercontent.com/16543074/89557980-415f8e80-d831-11ea-9d57-d6a1e6ed379b.PNG)
