### ISSUE TITLE
How to get the directory where the script is located?

### ISSUE THREAD

**Issue by KeesCBakker** [axilleasiv/vscode-javascript-repl-docs#25]
When I do some file IO I need to read files from the same directory the file is located in, but I'm not sure how I can change the work directory to something that is relative to the script.

I'm working on Windows, and what I get back is:

![image](https://user-images.githubusercontent.com/583193/100768660-6f2d9c00-33fb-11eb-9132-8ee3a12a38d1.png)

Would be nice if the `__dirname`  contains the `\` or `/` characters. Might it be a bug?

Awesome extension BTW! Keep up the good work 🥇

**Comment by axilleasiv** [comment]
In this case, I see two things that don't work as is expected. 

The first is that the `process.cwd()` does not show the relative dir path to the file that users are running the repl, so in your example, it should show `C:\\projects\\advent-of-code-2020`. It seems that it work as expected if you choose the `Node` option in [configuration](https://github.com/axilleasiv/vscode-javascript-repl-docs/wiki/Configuration#context) but it does not work as expected if users have selected the default `VM` option. So you may try to change this option and I think that your example will not have any error.

The second is that the in `__dirname` and `__filename` paths, the backslash chars `\` have been stripped from the path. It seems that in Unix environments the slashes in these paths are not stripped but I have reproduced it and is happening in windows.

@KeesCBakker thank you so much for your feedback and I am sorry about this, I will mark this as a bug and I hope to be fixed to the next version that will be released.

**Comment by KeesCBakker** [comment]
Hello @axilleasiv, good to know! That helps me a lot. I can confirm that it work the way you described on Windows.

I can also confirm the `__dirname` and `__filename` problem are also on the `Node` option: 
![image](https://user-images.githubusercontent.com/583193/101236161-2281e380-36cf-11eb-9459-0c26f35fb887.png)

BTW: it is a lot of fun to do Advent of Code this way!

**Comment by axilleasiv** [comment]
This has been fixed on the new version and all the paths about `__filename`, `__dirname` and `process.cwd()` in the windows environment are the right ones. The only unsupported feature at the moment is that if users want to read a file that is relative to the current working directory for example `const data = fs.readFileSync('./data.txt');`, they need to choose the `Node` option as [runtime context](https://github.com/axilleasiv/vscode-javascript-repl-docs/wiki/Configuration#context).
