### ISSUE TITLE
Context menu

### ISSUE THREAD

**Issue by andokai** [axilleasiv/vscode-javascript-repl-docs#26]
Hi there, first of all thanks for the extension, it's quite helpful.

Is it possible to update it so that it's not sitting on top of the context menu or perhaps add a config setting so that the context menu can be turned on and off? It's currently breaking years of muscle memory.

**Comment by axilleasiv** [comment]
Hi @andokai, I am adding this as a feature for the next release. At the moment I don't know if I will change the order of the context menu items or provide a config setting to enable/disable the context menu items about the repl. Maybe to add, both options.

Thank you so much for your feedback and If you have any other issue or you think that any feature is missing, feel free to post about it.

**Comment by axilleasiv** [comment]
@andokai this has been added to the new version. Now, the repl menu items are sitting at the bottom of the context menu.

<img width="360" alt="Screenshot 2021-01-23 at 20 23 07" src="https://user-images.githubusercontent.com/1872682/105616653-49ac8580-5de1-11eb-943d-1413c628a72c.png">

Also, a config option `JavaScript-repl: Menu Items On Context` has been added for users that they want to hide all the extension's menu items in the context menu.

**Comment by andokai** [comment]
Awesome, thanks! 👍
