### ISSUE TITLE
'JS Repl: Run' command does not work on js-files

### ISSUE THREAD

**Issue by VKondakoff** [axilleasiv/vscode-javascript-repl-docs#4]
Hello!

Looks like 'JS Repl: Run' command does not work on js-files. When I'm opening a js-file and run Cmd-Shit-P -> 'JS Repl: Run' command, I'm receiving an error 'The "from" argument must be of type string. Received type undefined'.

<img width="1082" alt="Image on 2019-11-13 03 11 25 PM" src="https://user-images.githubusercontent.com/230824/68763021-76cfa680-0628-11ea-84f8-2ce03ad7ecee.png">

The same happens when you issue this command on newly created (not saved) file, which Language Mode is set to JavaScript.

The command 'JS Repl: New JavaScript file (js) is working fine.

Description: Interactive Javascript Playground
Version: 0.6.1
VSCode: Version: 1.40.0
macOS Catalina

**Comment by VKondakoff** [comment]
So, currently there is no way to run JS Repl on existing file. :(

**Comment by axilleasiv** [comment]
Hello, @VKondakoff thank you so much for your feedback. When you are opening an existed and saved JS file and run Cmd-Shit-P -> 'JS Repl: Run' command and you see the error 'The "from" argument must be of type string. Received type undefined'. 

Can you please run the following command after you see this error. Cmd-Shit-P -> 'JS Repl: Show log file of active session' and copy-paste here the contents of this log file. Maybe there is more information about this error.

**Comment by VKondakoff** [comment]
There is no log file, until you actually run JS Repl:

<img width="468" alt="Image on 2019-11-13 04 14 55 PM" src="https://user-images.githubusercontent.com/230824/68766993-fcefeb00-0630-11ea-98b2-dcd914f3a227.png">

Here is what I have done: 
1. Start VSCode
2. Run 'JS Repl: New JavaScript file (js)' command
3. Open an existing js-file
4. Run 'JS Repl: Run' command (there is an error: 'The "from" argument must be of type string. Received type undefined')
5. Run 'JS Repl: Show log file of active session' command.

Here is the output:

`{"logs": [{"platform": "darwin"},{"jsdom":{"installed":false,"enabled":false},"asyncEnd":{"installed":false}},{"type":"init","args":{"filePath":"/Users/valerykondakoff/.js-repl/temp/2019-11-13T131530432/temp.js","filename":"temp.js","relativeDir":"/Users/valerykondakoff/.js-repl/temp/2019-11-13T131530432","id":"vs.editor.ICodeEditor:2,$model4","replId":"2019-11-13T131530432","version":"1.40.0","fileExtension":".js","rootDir":"/Users/valerykondakoff/.js-repl/temp/2019-11-13T131530432","useWorkers":false,"coverage":true,"context":"VM","included":["temp.js"],"outRootDir":"/Users/valerykondakoff/.js-repl","outDir":"/Users/valerykondakoff/.js-repl/temp/2019-11-13T131530432","logsDir":"/Users/valerykondakoff/.js-repl/logs","extensionDir":"/Users/valerykondakoff/.vscode/extensions/achil.vscode-javascript-repl-0.6.1","untitled":"Untitled-1","guttersDir":"/Users/valerykondakoff/.js-repl/images","doc":{"line":0,"idx":0}}},`

**Comment by axilleasiv** [comment]
@VKondakoff thank you for the log contents. I am trying to reproduce this with no success. I am testing in macOS High Sierra. I will try later with macOS Catalina.

Can you please try one last time the following steps:

1. Start VSCode
2. Open an existing js-file
3. Run 'JS Repl: Run' command
4. Run 'JS Repl: Show log file of active session' command.
5. Copy-paste again the contents, if any

**Comment by VKondakoff** [comment]
This will not work: the step 3 does not actually launch JS Repl, so there will be an error on step 4: 'Unable to open log'.

Here are my steps:

1. Start VSCode
2. Open an existing js-file
3. Run 'JS Repl: Run' command (Error!)
4. Run 'JS Repl: Show log' (Error!)
5. Run 'JS Repl New JavaScript file'
6. Open another existing js-file
7. Run 'JS Repl: Run' command (Error!)
8. Run 'JS Repl: Show log'

Here is the output:

`{"logs": [{"platform": "darwin"},{"jsdom":{"installed":false,"enabled":false},"asyncEnd":{"installed":false}},{"type":"init","args":{"filePath":"/Users/valerykondakoff/.js-repl/temp/2019-11-13T134821378/temp.js","filename":"temp.js","relativeDir":"/Users/valerykondakoff/.js-repl/temp/2019-11-13T134821378","id":"vs.editor.ICodeEditor:2,$model3","replId":"2019-11-13T134821378","version":"1.40.0","fileExtension":".js","rootDir":"/Users/valerykondakoff/.js-repl/temp/2019-11-13T134821378","useWorkers":false,"coverage":true,"context":"VM","included":["temp.js"],"outRootDir":"/Users/valerykondakoff/.js-repl","outDir":"/Users/valerykondakoff/.js-repl/temp/2019-11-13T134821378","logsDir":"/Users/valerykondakoff/.js-repl/logs","extensionDir":"/Users/valerykondakoff/.vscode/extensions/achil.vscode-javascript-repl-0.6.1","untitled":"Untitled-1","guttersDir":"/Users/valerykondakoff/.js-repl/images","doc":{"line":0,"idx":0}}},`

**Comment by axilleasiv** [comment]
Thank you @VKondakoff one more time for your feedback. I will look into this bug further and I will let you know when it will be fixed.

**Comment by VKondakoff** [comment]
Thanks. Ready to test something, if needed.

**Comment by VKondakoff** [comment]
Here is additional info: if I choose 'JS Repl New JavaScript file' command and then save the newly created file, the JS Repl session ends at the moment, when file is saved. Is this expected behaviour?

**Comment by axilleasiv** [comment]
@VKondakoff Yes, at this first release, this is the expected behavior. It is supposed that after users save their files, they can just Cmd-Shit-P -> 'JS Repl: Run' in the saved file. But for you, this is not working and I am still wondering why. I have tested the extension in macOS Catalina and for me, is working properly. 

I am thinking that two possible problems that may prevent the extension to run in an existed JavaScript file are the node.js version that is installed on your machine or some imported CSS files inside the code that is not fully supported yet(like CSS modules).

Although most of the time that I was writing this extension I was using node.js v.10.2.0, it is better for the users to have installed at least the node.js v.10.15.0. So if you have an older version than 10.15.0, please try to install this or a newer node.js version.

If I had installed this or a newer node.js version installed in my machine, I would try first to repl a minimal example like the following:
```
console.log('Test');
``` 
If you try any of the above, please let me if you still have problems.

**Comment by VKondakoff** [comment]
Hello, again! I have node.js 13.1.0 installed here:

<img width="1073" alt="Image on 2019-11-14 01 04 11 PM" src="https://user-images.githubusercontent.com/230824/68848052-b2c64280-06e0-11ea-9d9e-6e0fd5b83805.png">

'console.log('Test');' works great on node.js repl.

BTW, I just checked (to be sure): Cmd-Shit-P -> 'JS Repl: Run' command does not run on all other supported file formats as well: CoffeeScript, TypeScript, React, TypeScript React with the same error 'The "from" argument must be of type string. Received type undefined'.

**Comment by VKondakoff** [comment]
OK, nailed it!..

It turns out, the Cmd-Shit-P -> 'JS Repl: Run' command does not work if there is no folder currently open in VSCode Explorer. To reproduce, choose File -> Close Folder menu item and try to run Cmd-Shit-P -> 'JS Repl: Run' command.

If there is any folder open in VSCode explorer, Cmd-Shit-P -> 'JS Repl: Run' command works as expected (I thing 'from' argument is the name (path?) of the folder).

Can you reproduce this?

**Comment by axilleasiv** [comment]
Oh, @VKondakoff  that's it!!  👏

I was worried enough to support multi folders on a single workspace and I am not handling properly the case that no folder is opened in the editor or there is no package.json file in their folder. Under the hood, the extension uses this function https://github.com/axilleasiv/parcel/blob/master/packages/core/parcel-bundler/src/Resolver.js#L430 to resolve the folder root path of a filename.

So, currently, users need to have one folder at least in their workspace and a package.json in this folder or a parent folder in order the 'Run' command to works. But I want this case to be supported properly, so I have added this issue, for the next milestone release.

VKondakoff, your help is really appreciated, thank you again for your feedback!

**Comment by axilleasiv** [comment]
fixed in 0.6.2 version
